# 3.5.20 Pandas Part 2

### Command Line 101

#### Unix (Mac OS / Linux)

- Open a Terminal in the **3.11.27 Pandas** folder (check [this tutorial](https://www.maketecheasier.com/launch-terminal-current-folder-mac/) for a refresher) 
- Use the command `ls` to check the contents of the directory
- Use the command `cd data` to move into the **data** folder *(cd = change directory)*
- Use the command `echo "hello world" > file.txt` to create a new file **file.txt** and write the string **hello world** inside it
- Use the command `cat file.txt` to check the contents of the file
- Use the command `wc -l file.txt` to count the number of rows in the file

Check out [this page](https://www.earthdatascience.org/courses/intro-to-earth-data-science/open-reproducible-science/bash/bash-commands-to-manage-directories-files/) and [this video](https://www.youtube.com/watch?v=SgGFZvlqcwk) for more useful commands on how to work with files and dierctories.

#### Windows

*Note: Windows users with Windows 10 or higher can [activate the Windows Subsystem for Linux (WSL)](https://www.laptopmag.com/articles/use-bash-shell-windows-10), which will enable the Linux Bash Shell in Windows 10.*

- Open a Command Prompt in the **3.11.27 Pandas** folder (check [this tutorial](https://www.lifewire.com/open-command-prompt-in-a-folder-5185505) for a refresher) 
- Use the command `dir` to check the contents of the directory
- Use the command `cd data` to move into the **data** folder *(cd = change directory)*
- Use the command `echo hello world > file.txt` to create a new file **file.txt** and write the string **hello world** inside it
- Use the command `type file.txt` to check the contents of the file
- Use the command `find /v /c "" file.txt` to count the number of rows in the file

Check out this [list of commands](https://www.ionos.com/digitalguide/server/know-how/windows-cmd-commands/) as well as these videos on [navigating the file system](https://www.youtube.com/watch?v=9zMWXD-xoxc) and [working with files](https://www.youtube.com/watch?v=tqdiGfF68cc).

---

### Reading data in

There are plenty of [pandas functions for reading tabular data](https://wesmckinney.com/book/accessing-data.html#tbl-table_parsing_functions) as a DataFrame; one of the most frequently used is `pd.read_csv` which has a long list of optional parameters that can help you deal with exceptions and messy data in the data loading process. Nevertheless, if your dataset is fairly clean, you can load a .csv file in one line of code, just like in the following example. 

Let's load the **iris** dataset, which is a very famous dataset among statisticians, it was introduced by the British statistician and biologist Ronald Fisher in 1936. 

The data set consists of 50 samples from each of **three species of Iris** (setosa, virginica and versicolor) for a total of 150 observations. Four features were measured from each sample: the **length and the width of the sepals and petals**, in centimeters. Based on the combination of these four features, Fisher developed a linear discriminant model to distinguish the species from each other.

Before loading the dataset, let's quickly inspect it and check the number of records using the command line: 

- Use the command `head -10 iris.csv` to see the first 10 rows of a dataset. Head is similar to cat but allows us to specify how many rows we want to inspect
- Use the command `wc -l iris.csv` to see how many rows are in the dataset

In [3]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [4]:
import pandas as pd
# read the data and save it to an DataFrame object
iris = pd.read_csv("/content/gdrive/MyDrive/Sander Mulder/python folder/Pandas 2/data/iris.csv")

In [5]:
# let's check the data type of object iris
type(iris)

pandas.core.frame.DataFrame

In [6]:
# let's check its number of rows and columns
iris.shape

(150, 5)

In [7]:
# let's print the first five rows of the data
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

Let's check how many observations we have for each `variety`:

In [8]:
iris["variety"].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

Let's say we're interested in the average `petal.length` for each variety, therefore we'll be interested in this portion of the dataset:

In [9]:
iris.loc[:,["petal.length","variety"]]

     petal.length    variety
0             1.4     Setosa
1             1.4     Setosa
2             1.3     Setosa
3             1.5     Setosa
4             1.4     Setosa
..            ...        ...
145           5.2  Virginica
146           5.0  Virginica
147           5.2  Virginica
148           5.4  Virginica
149           5.1  Virginica

[150 rows x 2 columns]

We can filter the dataset so to keep just the rows of the Setosa variety in the following way:

In [10]:
iris.loc[iris["variety"]=="Setosa",["petal.length","variety"]].head()

   petal.length variety
0           1.4  Setosa
1           1.4  Setosa
2           1.3  Setosa
3           1.5  Setosa
4           1.4  Setosa

At this point, I can calculate the average petal length by simply taking the average of the `petal.length` column:

In [ ]:
iris.loc[iris["variety"]=="Setosa","petal.length"].mean()

1.4620000000000002

In [ ]:
print("Avg. petal length by iris variety:")
print("Setosa:", iris.loc[iris["variety"]=="Setosa"]["petal.length"].mean())
print("Versicolor:", iris.loc[iris["variety"]=="Versicolor"]["petal.length"].mean())
print("Virginica:", iris.loc[iris["variety"]=="Virginica"]["petal.length"].mean())

Avg. petal length by iris variety:
Setosa: 1.4620000000000002
Versicolor: 4.26
Virginica: 5.552

In [ ]:
print("Avg. petal length by iris variety:")
for var in iris["variety"].unique(): 
    print(var, ":", iris.loc[iris["variety"]==var]["petal.length"].mean())

Avg. petal length by iris variety:
Setosa : 1.4620000000000002
Versicolor : 4.26
Virginica : 5.552

Let's see how to **load a slightly messier dataset**. You can find the `GA Paid Search Traffic.csv` file in the `data` folder, which was generated and downloaded from the **Paid Keyword report** in the **Google Analytics** account of the Google Merchandise Store: *Acquisition > Campaigns > Paid Keywords*. 

By inspecting the dataset via the command line we notice that there are three main blocks of information: 

`cat "GA Paid Search Traffic.csv"`

- a header containing some metadata information 
- a first block of data related to paid keyword performance
- a second block of data containing a time series with the number of users

If we try to read the file as is, we will get an error, line in the block below:

In [12]:
# read the data and save it to an DataFrame object
GA = pd.read_csv("/content/gdrive/MyDrive/Sander Mulder/python folder/Pandas 2/data/GA Paid Search Traffic.csv")

ParserError: ignored

Let's refer back to the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) of the `pd.read_csv()` function to see which parameters could come in handy here. In particular the following two paramenters will help us deal with this file:

- **skiprows**: number of lines to skip (int) at the start of the file
- **nrows**: number of rows of file to read

In [14]:
ga_keywords = pd.read_csv("/content/gdrive/MyDrive/Sander Mulder/python folder/Pandas 2/data/GA Paid Search Traffic.csv", skiprows=5, nrows=10)
ga_keywords

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,"1,051",753,"1,455",27.29%,5.62,00:03:41,0.34%,5,US$256.96
1,(not set),546,346,759,29.78%,5.32,00:03:18,0.13%,1,US$12.99
2,google merch,103,82,145,28.28%,6.04,00:03:29,2.07%,3,US$86.09
3,google backpack,95,68,121,40.50%,4.20,00:02:27,0.00%,0,US$0.00
4,Google Merchandise,93,54,147,28.57%,5.37,00:03:23,0.68%,1,US$79.98
5,Google Apparel,92,76,127,37.80%,4.97,00:03:11,0.79%,1,US$76.37
6,youtuber merch,78,76,82,78.05%,1.41,00:00:06,0.00%,0,US$0.00
7,Google Swag,63,57,80,41.25%,5.10,00:04:14,0.00%,0,US$0.00
8,google merch store,54,38,69,28.99%,5.09,00:02:33,0.00%,0,US$0.00
9,Google Clothing,39,36,49,40.82%,3.98,00:02:43,0.00%,0,US$0.00

It's always important to **check the data type of the DataFrame's columns** after loading the data; you always want to ensure that the data has been imported as expected. You can use the `.dtype` attribute or the `.info()` method on the DataFrame to get a table showing the data type for each column of the DataFrame. 

*Notice that the `object` data type is a string.* 

Check out the table below for a more [detailed explanation](https://pbpython.com/pandas_dtypes.html) of data types in `pandas`: 

<img src="img/pandas-dtypes.png" width="600">

Let's check the data type of each column of the `ga_keywords` DataFrame using the `.info()` method:

In [15]:
ga_keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Keyword                     10 non-null     object
 1   Users                       10 non-null     object
 2   New Users                   10 non-null     int64
 3   Sessions                    10 non-null     object
 4   Bounce Rate                 10 non-null     object
 5   Pages/Session               10 non-null     float64
 6   Avg. Session Duration       10 non-null     object
 7   E-commerce Conversion Rate  10 non-null     object
 8   Transactions                10 non-null     int64
 9   Revenue                     10 non-null     object
dtypes: float64(1), int64(2), object(7)
memory usage: 928.0+ bytes

The verdict is that some columns have been interpreted correctly, others not so much; I'll report just the changes that need to be done: 

- **Users** & **Sessions** --> remove the "," sign & convert from string to int
- **Bounce Rate** & **E-commerce Conversion Rate** --> remove % sign & convert from string to float
- **Revenue** --> remove US$ sign & convert from string to float

Let's start with Users & Sessions. The issue here is that the `,`, which represents the thousands separator, is making Python think that this is a string and not an integer, so we'll need to use the `.replace()` method to find a `,` and replace it with nothing:

In [16]:
ga_keywords["Users"].str.replace(',', '').astype('int64')

0    1051
1     546
2     103
3      95
4      93
5      92
6      78
7      63
8      54
9      39
Name: Users, dtype: int64

In [17]:
# remove comma & convert to int
ga_keywords["Users"] = ga_keywords["Users"].str.replace(',', '').astype('int64')
ga_keywords["Sessions"] = ga_keywords["Sessions"].str.replace(',', '').astype('int64')
# remove % & convert to float
ga_keywords["Bounce Rate"] = ga_keywords["Bounce Rate"].str.replace('%', '').astype('float64')
ga_keywords["E-commerce Conversion Rate"] = ga_keywords["E-commerce Conversion Rate"].str.replace('%', '').astype('float64')
# remuve US$ & convert to float
ga_keywords["Revenue"] = ga_keywords["Revenue"].str.replace('US$', '', regex=False).astype('float64')

In [18]:
ga_keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Keyword                     10 non-null     object
 1   Users                       10 non-null     int64
 2   New Users                   10 non-null     int64
 3   Sessions                    10 non-null     int64
 4   Bounce Rate                 10 non-null     float64
 5   Pages/Session               10 non-null     float64
 6   Avg. Session Duration       10 non-null     object
 7   E-commerce Conversion Rate  10 non-null     float64
 8   Transactions                10 non-null     int64
 9   Revenue                     10 non-null     float64
dtypes: float64(4), int64(4), object(2)
memory usage: 928.0+ bytes

In [19]:
ga_keywords

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,1455,27.29,5.62,00:03:41,0.34,5,256.96
1,(not set),546,346,759,29.78,5.32,00:03:18,0.13,1,12.99
2,google merch,103,82,145,28.28,6.04,00:03:29,2.07,3,86.09
3,google backpack,95,68,121,40.50,4.20,00:02:27,0.00,0,0.00
4,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68,1,79.98
5,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79,1,76.37
6,youtuber merch,78,76,82,78.05,1.41,00:00:06,0.00,0,0.00
7,Google Swag,63,57,80,41.25,5.10,00:04:14,0.00,0,0.00
8,google merch store,54,38,69,28.99,5.09,00:02:33,0.00,0,0.00
9,Google Clothing,39,36,49,40.82,3.98,00:02:43,0.00,0,0.00

We see a `(not set)` keyword, which is not that meaningful to us, so we decide to remove it from our dataset using a boolean mask:

In [20]:
ga_keywords = ga_keywords[ga_keywords["Keyword"] != "(not set)"]
ga_keywords

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,1455,27.29,5.62,00:03:41,0.34,5,256.96
2,google merch,103,82,145,28.28,6.04,00:03:29,2.07,3,86.09
3,google backpack,95,68,121,40.50,4.20,00:02:27,0.00,0,0.00
4,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68,1,79.98
5,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79,1,76.37
6,youtuber merch,78,76,82,78.05,1.41,00:00:06,0.00,0,0.00
7,Google Swag,63,57,80,41.25,5.10,00:04:14,0.00,0,0.00
8,google merch store,54,38,69,28.99,5.09,00:02:33,0.00,0,0.00
9,Google Clothing,39,36,49,40.82,3.98,00:02:43,0.00,0,0.00

Finally, we notice that the index of the DataFrame is now skipping from 0 to 2, so let's reset the index to avoid possible future errors:

In [21]:
ga_keywords.reset_index(inplace=True, drop=True)
ga_keywords

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,1455,27.29,5.62,00:03:41,0.34,5,256.96
1,google merch,103,82,145,28.28,6.04,00:03:29,2.07,3,86.09
2,google backpack,95,68,121,40.50,4.20,00:02:27,0.00,0,0.00
3,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68,1,79.98
4,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79,1,76.37
5,youtuber merch,78,76,82,78.05,1.41,00:00:06,0.00,0,0.00
6,Google Swag,63,57,80,41.25,5.10,00:04:14,0.00,0,0.00
7,google merch store,54,38,69,28.99,5.09,00:02:33,0.00,0,0.00
8,Google Clothing,39,36,49,40.82,3.98,00:02:43,0.00,0,0.00

---

### Exercise

Using the same `GA Paid Search Traffic.csv` file from the `data` folder as before, and the `pd.read_csv()` function that we've been using so far, load the "third block of data" from the file, that is, the Users' time series data.

In [29]:
df = pd.read_csv("/content/gdrive/MyDrive/Sander Mulder/python folder/Pandas 2/data/GA Paid Search Traffic.csv",skiprows=19, nrows=29)
df

     Day Index  Users
0   01/05/2019     93
1   02/05/2019    114
2   03/05/2019    121
3   04/05/2019     69
4   05/05/2019     75
5   06/05/2019    109
6   07/05/2019    140
7   08/05/2019    148
8   09/05/2019    167
9   10/05/2019    135
10  11/05/2019     80
11  12/05/2019     60
12  13/05/2019    149
13  14/05/2019    117
14  15/05/2019    107
15  16/05/2019    116
16  17/05/2019    101
17  18/05/2019     65
18  19/05/2019     63
19  20/05/2019     58
20  21/05/2019     15
21  22/05/2019     61
22  23/05/2019    122
23  24/05/2019    114
24  25/05/2019     84
25  26/05/2019    118
26  27/05/2019    126
27  28/05/2019    142
28  29/05/2019     64